Updating iframe page based on the Issue 255
webrtc/test-pages pull request #22
Opened 2017-12-08 10:24 UTC by rantonysamy

Updating the iframe test page based on the comments at Issue 255.

Created a Table and Added the iframes in that so make sure the visitors of this page sees both the implementations in one single view.

2017-12-08 12:56 UTC, KaptenJansson requested changes

2017-12-08 12:56 UTC, KaptenJansson commented on src/iframe-apprtc/index.html
> +<table style="border:1px solid #000; witdh:100%;">
width is misspelled.

2017-12-08 12:56 UTC, KaptenJansson commented on src/iframe-apprtc/index.html
> +<table style="border:1px solid #000; witdh:100%;">
Also, please put all style attributes in the main css [file](https://github.com/webrtc/test-pages/tree/gh-pages/src/css). Make sure it does not conflict with other pages using the css file.

2017-12-08 12:56 UTC, KaptenJansson commented on src/iframe-apprtc/index.html
> +    <td style="border:1px solid #000; witdh:100%;"><iframe width="100%" height="600px" src="//appr.tc"></iframe></td>
width is misspelled.

2017-12-08 12:56 UTC, KaptenJansson commented on src/iframe-apprtc/index.html
> +    <td style="border:1px solid #000; witdh:100%;"><iframe width="100%" height="600px" src="//appr.tc" allow="geolocation; microphone; camera"></iframe></td>
width is misspelled.

2017-12-08 12:56 UTC, KaptenJansson commented on src/iframe-apprtc/index.html
> +    <td style="border:1px solid #000; witdh:100%;"><iframe width="100%" height="600px" src="//appr.tc"></iframe></td>
Could you also try to use percentage for height, I remember it can be a bit fiddly with iframes but maybe things have improved?

2017-12-11 10:09 UTC, KaptenJansson requested changes
LGTM overall, just one nit and one question.

2017-12-11 10:09 UTC, KaptenJansson commented on src/css/main.css
> +table, td, th {
Have you checked that this works with other pages in this repo as this will affect all of them using these tags?

2017-12-11 10:09 UTC, KaptenJansson commented on src/css/main.css
> + *  Copyright (c) 2017 The WebRTC project authors. All Rights Reserved.
Only set copyright for new files, no need to update.

2017-12-11 10:31 UTC, rantonysamy commented
The other place <table> used is https://webrtc.github.io/test-pages/src/multiple-video/ - this CSS only improve the look and feel of it, so no worries. Updating Copyright information with a Fixup next.

2017-12-11 10:46 UTC, rantonysamy commented
Sent 2 commits (should have sent only one, but missed one file for the first time). That should be able to address both the comments. kindly take a look.

2017-12-11 15:39 UTC, KaptenJansson approved these changes

2017-12-11 15:39 UTC, merged